# Database Configuration
database {
  url = "jdbc:postgresql://localhost:5432/finance_tracker"
  username = "finance_user"
  password = "finance_password"
  driver = "org.postgresql.Driver"
  maximumPoolSize = 10
  autoCommit = true
  connectionTimeout = 30000
}

# Liquibase Configuration
 liquibase {
#   #changeLog = "/app/db/changelog/master.xml"
#   searchPath = "classpath:/db/changelog/"
   changeLog = "db/changelog/master.xml"
   contexts = "development"
 }
